#pragma once

#include <ti/driverlib/dl_dma.h>
#include <ti/driverlib/dl_uart_main.h>

#if !defined(FAKE_MSPM0_G3519)
#error "The G3519 fake SysConfig header requires FAKE_MSPM0_G3519."
#endif

#define DeviceFamily_ID_MSPM0G351X 3519U
#define DeviceFamily_ID DeviceFamily_ID_MSPM0G351X

#define UART_0_INST UART0
#define UART_0_INST_INT_IRQN UART0_INT_IRQn
#define UART_0_INST_FREQUENCY 32000000U
#define UART_0_BAUD_RATE 115200U
#define UART_0_LIBXR_EXTEND_CAPABLE 1

#define UART_1_INST UART1
#define UART_1_INST_INT_IRQN UART1_INT_IRQn
#define UART_1_INST_FREQUENCY 32000000U
#define UART_1_BAUD_RATE 115200U
#define UART_1_LIBXR_EXTEND_CAPABLE 0

#define UART_3_INST UART3
#define UART_3_INST_INT_IRQN UART3_INT_IRQn
#define UART_3_INST_FREQUENCY 32000000U
#define UART_3_BAUD_RATE 115200U
#define UART_3_LIBXR_EXTEND_CAPABLE 0

#define UART_4_INST UART4
#define UART_4_INST_INT_IRQN UART4_INT_IRQn
#define UART_4_INST_FREQUENCY 32000000U
#define UART_4_BAUD_RATE 115200U
#define UART_4_LIBXR_EXTEND_CAPABLE 0

#define UART_5_INST UART5
#define UART_5_INST_INT_IRQN UART5_INT_IRQn
#define UART_5_INST_FREQUENCY 32000000U
#define UART_5_BAUD_RATE 115200U
#define UART_5_LIBXR_EXTEND_CAPABLE 0

#define UART_6_INST UART6
#define UART_6_INST_INT_IRQN UART6_INT_IRQn
#define UART_6_INST_FREQUENCY 32000000U
#define UART_6_BAUD_RATE 115200U
#define UART_6_LIBXR_EXTEND_CAPABLE 0

#define UART_7_INST UART7
#define UART_7_INST_INT_IRQN UART7_INT_IRQn
#define UART_7_INST_FREQUENCY 32000000U
#define UART_7_BAUD_RATE 115200U
#define UART_7_LIBXR_EXTEND_CAPABLE 1

#define DMA_CH0_CHAN_ID 0U
#define DMA_CH1_CHAN_ID 1U
#define DMA_CH2_CHAN_ID 2U
#define DMA_CH3_CHAN_ID 3U
#define DMA_CH4_CHAN_ID 4U
#define DMA_CH5_CHAN_ID 5U
#define DMA_CH6_CHAN_ID 6U
#define DMA_CH7_CHAN_ID 7U
#define DMA_CH8_CHAN_ID 8U
#define DMA_CH9_CHAN_ID 9U
#define DMA_CH10_CHAN_ID 10U
#define DMA_CH11_CHAN_ID 11U

#define LIBXR_MSPM0_DMA_DISPATCHER_AVAILABLE 1

#define DMA_CH0_LIBXR_UART_IRQN UART0_INT_IRQn
#define DMA_CH0_LIBXR_UART_TX 1
#define DMA_CH1_LIBXR_UART_IRQN UART0_INT_IRQn
#define DMA_CH1_LIBXR_UART_RX 1
#define DMA_CH1_LIBXR_FULL_CHANNEL 1
#define DMA_CH1_LIBXR_HALF_INTERRUPT 1

#define DMA_CH2_LIBXR_UART_IRQN UART7_INT_IRQn
#define DMA_CH2_LIBXR_UART_TX 1
#define DMA_CH3_LIBXR_UART_IRQN UART7_INT_IRQn
#define DMA_CH3_LIBXR_UART_RX 1
#define DMA_CH3_LIBXR_FULL_CHANNEL 1
#define DMA_CH3_LIBXR_HALF_INTERRUPT 0

#define DMA_CH4_LIBXR_UART_IRQN UART1_INT_IRQn
#define DMA_CH4_LIBXR_UART_TX 1
#define DMA_CH5_LIBXR_UART_IRQN UART3_INT_IRQn
#define DMA_CH5_LIBXR_UART_TX 1
#define DMA_CH6_LIBXR_UART_IRQN UART4_INT_IRQn
#define DMA_CH6_LIBXR_UART_TX 1
#define DMA_CH7_LIBXR_UART_IRQN UART5_INT_IRQn
#define DMA_CH7_LIBXR_UART_TX 1
#define DMA_CH8_LIBXR_UART_IRQN UART6_INT_IRQn
#define DMA_CH8_LIBXR_UART_TX 1

#define UART_0_LIBXR_TX_DMA DMA_CH0
#define UART_0_LIBXR_TX_DMA_CHANNEL DMA_CH0_CHAN_ID
#define UART_0_LIBXR_TX_DMA_TRIGGER DMA_UART0_TX_TRIG
#define UART_0_LIBXR_RX_DMA DMA_CH1
#define UART_0_LIBXR_RX_DMA_CHANNEL DMA_CH1_CHAN_ID
#define UART_0_LIBXR_RX_DMA_TRIGGER DMA_UART0_RX_TRIG

#define UART_7_LIBXR_TX_DMA DMA_CH2
#define UART_7_LIBXR_TX_DMA_CHANNEL DMA_CH2_CHAN_ID
#define UART_7_LIBXR_TX_DMA_TRIGGER DMA_UART7_TX_TRIG
#define UART_7_LIBXR_RX_DMA DMA_CH3
#define UART_7_LIBXR_RX_DMA_CHANNEL DMA_CH3_CHAN_ID
#define UART_7_LIBXR_RX_DMA_TRIGGER DMA_UART7_RX_TRIG

#define UART_1_LIBXR_TX_DMA DMA_CH4
#define UART_1_LIBXR_TX_DMA_CHANNEL DMA_CH4_CHAN_ID
#define UART_1_LIBXR_TX_DMA_TRIGGER DMA_UART1_TX_TRIG
#define UART_3_LIBXR_TX_DMA DMA_CH5
#define UART_3_LIBXR_TX_DMA_CHANNEL DMA_CH5_CHAN_ID
#define UART_3_LIBXR_TX_DMA_TRIGGER DMA_UART3_TX_TRIG
#define UART_4_LIBXR_TX_DMA DMA_CH6
#define UART_4_LIBXR_TX_DMA_CHANNEL DMA_CH6_CHAN_ID
#define UART_4_LIBXR_TX_DMA_TRIGGER DMA_UART4_TX_TRIG
#define UART_5_LIBXR_TX_DMA DMA_CH7
#define UART_5_LIBXR_TX_DMA_CHANNEL DMA_CH7_CHAN_ID
#define UART_5_LIBXR_TX_DMA_TRIGGER DMA_UART5_TX_TRIG
#define UART_6_LIBXR_TX_DMA DMA_CH8
#define UART_6_LIBXR_TX_DMA_CHANNEL DMA_CH8_CHAN_ID
#define UART_6_LIBXR_TX_DMA_TRIGGER DMA_UART6_TX_TRIG

inline void SYSCFG_DL_init() {}
