/**
 * @file print_config_reset.hpp
 * @brief 打印配置编译检查使用的宏清理。 /
 * Macro reset helper for print configuration compile checks.
 *
 * 清除外部打印开关，让每个检查文件显式设置所需配置。
 * Clears external print switches so each probe defines its own configuration.
 */

#pragma once

#undef LIBXR_PRINT_ENABLE_INTEGER
#undef LIBXR_PRINT_ENABLE_TEXT
#undef LIBXR_PRINT_ENABLE_POINTER
#undef LIBXR_PRINT_ENABLE_FLOAT
#undef LIBXR_PRINT_INTEGER_ENABLE_BASE8_16
#undef LIBXR_PRINT_INTEGER_ENABLE_64BIT
#undef LIBXR_PRINT_FLOAT_ENABLE_FIXED
#undef LIBXR_PRINT_FLOAT_ENABLE_DOUBLE
#undef LIBXR_PRINT_FLOAT_ENABLE_SCIENTIFIC
#undef LIBXR_PRINT_FLOAT_ENABLE_GENERAL
#undef LIBXR_PRINT_FLOAT_ENABLE_LONG_DOUBLE
#undef LIBXR_PRINT_FLOAT_MAX_PRECISION
#undef LIBXR_PRINT_FLOAT_MAX_INTEGER_DIGITS
#undef LIBXR_PRINT_ENABLE_WIDTH
#undef LIBXR_PRINT_ENABLE_PRECISION
#undef LIBXR_PRINT_ENABLE_ALTERNATE
#undef LIBXR_PRINT_ENABLE_EXPLICIT_ARGUMENT_INDEXING
