# Detect system
# Preserve user-provided cache variables and normalize them only for internal use.
set(_xr_system "")
if(DEFINED LIBXR_SYSTEM AND NOT "${LIBXR_SYSTEM}" STREQUAL "")
  string(TOLOWER "${LIBXR_SYSTEM}" _xr_system)
  if(NOT "${LIBXR_SYSTEM}" STREQUAL "${_xr_system}")
    message(STATUS "Normalized LIBXR_SYSTEM: ${LIBXR_SYSTEM} -> ${_xr_system}")
  endif()
endif()

set(_xr_driver "")
if(DEFINED LIBXR_DRIVER AND NOT "${LIBXR_DRIVER}" STREQUAL "")
  string(TOLOWER "${LIBXR_DRIVER}" _xr_driver)
  if(NOT "${LIBXR_DRIVER}" STREQUAL "${_xr_driver}")
    message(STATUS "Normalized LIBXR_DRIVER: ${LIBXR_DRIVER} -> ${_xr_driver}")
  endif()
endif()

if(CMAKE_CROSSCOMPILING)
  message(STATUS "Cross compiling.")
elseif(NOT _xr_system)
  if(CMAKE_HOST_SYSTEM_NAME MATCHES "Linux")
    if(WEBOTS_HOME)
      set(_xr_system "webots")
      set(_xr_driver "webots")
    else()
      set(_xr_system "linux")
      set(_xr_driver "linux")
    endif()
  elseif(CMAKE_HOST_SYSTEM_NAME MATCHES "Windows")
    set(_xr_system "windows")
    set(_xr_driver "windows")
  else()
    message(FATAL_ERROR "Unknown system.")
  endif()
endif()

if(NOT _xr_system)
  message(FATAL_ERROR "No system selected.")
endif()

target_compile_definitions(${PROJECT_NAME} PUBLIC LIBXR_SYSTEM_${_xr_system}=True)

if(_xr_system STREQUAL "linux" OR _xr_system STREQUAL "webots")
  target_compile_definitions(${PROJECT_NAME} PUBLIC LIBXR_SYSTEM_POSIX_HOST=True)
endif()

if(_xr_driver)
  include(${CMAKE_CURRENT_LIST_DIR}/../driver/${_xr_driver}/CMakeLists.txt)
else()
  message(WARNING "No driver selected.")
endif()

include(${CMAKE_CURRENT_LIST_DIR}/../system/${_xr_system}/CMakeLists.txt)

message(STATUS "Platform: ${_xr_system}")

if(NOT DEFINED LIBXR_DEFAULT_SCALAR)
  set(LIBXR_DEFAULT_SCALAR double)
endif()

if(NOT DEFINED LIBXR_PRINTF_BUFFER_SIZE)
  set(LIBXR_PRINTF_BUFFER_SIZE 128)
endif()

if(NOT DEFINED LIBXR_LOG_LEVEL)
  set(LIBXR_LOG_LEVEL 4)
endif()

if(NOT DEFINED LIBXR_LOG_OUTPUT_LEVEL)
  set(LIBXR_LOG_OUTPUT_LEVEL 4)
endif()

if(NOT DEFINED XR_LOG_MESSAGE_MAX_LEN)
  set(XR_LOG_MESSAGE_MAX_LEN 64)
endif()

if(NOT DEFINED LIBXR_PRINT_ENABLE_INTEGER)
  set(LIBXR_PRINT_ENABLE_INTEGER 1)
endif()

if(NOT DEFINED LIBXR_PRINT_ENABLE_TEXT)
  set(LIBXR_PRINT_ENABLE_TEXT 1)
endif()

if(NOT DEFINED LIBXR_PRINT_ENABLE_POINTER)
  set(LIBXR_PRINT_ENABLE_POINTER 1)
endif()

if(NOT DEFINED LIBXR_PRINT_ENABLE_FLOAT)
  set(LIBXR_PRINT_ENABLE_FLOAT 1)
endif()

if(NOT DEFINED LIBXR_PRINT_INTEGER_ENABLE_BASE8_16)
  set(LIBXR_PRINT_INTEGER_ENABLE_BASE8_16 1)
endif()

if(NOT DEFINED LIBXR_PRINT_INTEGER_ENABLE_64BIT)
  if(LIBXR_TEST_BUILD)
    set(LIBXR_PRINT_INTEGER_ENABLE_64BIT 1)
  else()
    set(LIBXR_PRINT_INTEGER_ENABLE_64BIT 0)
  endif()
endif()

if(NOT DEFINED LIBXR_PRINT_FLOAT_ENABLE_FIXED)
  set(LIBXR_PRINT_FLOAT_ENABLE_FIXED 1)
endif()

if(NOT DEFINED LIBXR_PRINT_FLOAT_ENABLE_DOUBLE)
  if(LIBXR_TEST_BUILD)
    set(LIBXR_PRINT_FLOAT_ENABLE_DOUBLE 1)
  else()
    set(LIBXR_PRINT_FLOAT_ENABLE_DOUBLE 0)
  endif()
endif()

if(NOT DEFINED LIBXR_PRINT_FLOAT_ENABLE_SCIENTIFIC)
  set(LIBXR_PRINT_FLOAT_ENABLE_SCIENTIFIC 1)
endif()

if(NOT DEFINED LIBXR_PRINT_FLOAT_ENABLE_GENERAL)
  set(LIBXR_PRINT_FLOAT_ENABLE_GENERAL 1)
endif()

if(NOT DEFINED LIBXR_PRINT_FLOAT_ENABLE_LONG_DOUBLE)
  if(LIBXR_TEST_BUILD)
    set(LIBXR_PRINT_FLOAT_ENABLE_LONG_DOUBLE 1)
  else()
    set(LIBXR_PRINT_FLOAT_ENABLE_LONG_DOUBLE 0)
  endif()
endif()

if(NOT DEFINED LIBXR_PRINT_ENABLE_WIDTH)
  set(LIBXR_PRINT_ENABLE_WIDTH 1)
endif()

if(NOT DEFINED LIBXR_PRINT_ENABLE_PRECISION)
  set(LIBXR_PRINT_ENABLE_PRECISION 1)
endif()

target_compile_definitions(
  ${PROJECT_NAME}
  PUBLIC LIBXR_DEFAULT_SCALAR=${LIBXR_DEFAULT_SCALAR}
  PUBLIC LIBXR_PRINTF_BUFFER_SIZE=${LIBXR_PRINTF_BUFFER_SIZE}
  PUBLIC LIBXR_LOG_LEVEL=${LIBXR_LOG_LEVEL}
  PUBLIC LIBXR_LOG_OUTPUT_LEVEL=${LIBXR_LOG_OUTPUT_LEVEL}
  PUBLIC XR_LOG_MESSAGE_MAX_LEN=${XR_LOG_MESSAGE_MAX_LEN}
  PUBLIC LIBXR_PRINT_ENABLE_INTEGER=$<BOOL:${LIBXR_PRINT_ENABLE_INTEGER}>
  PUBLIC LIBXR_PRINT_ENABLE_TEXT=$<BOOL:${LIBXR_PRINT_ENABLE_TEXT}>
  PUBLIC LIBXR_PRINT_ENABLE_POINTER=$<BOOL:${LIBXR_PRINT_ENABLE_POINTER}>
  PUBLIC LIBXR_PRINT_ENABLE_FLOAT=$<BOOL:${LIBXR_PRINT_ENABLE_FLOAT}>
  PUBLIC LIBXR_PRINT_INTEGER_ENABLE_BASE8_16=$<BOOL:${LIBXR_PRINT_INTEGER_ENABLE_BASE8_16}>
  PUBLIC LIBXR_PRINT_INTEGER_ENABLE_64BIT=$<BOOL:${LIBXR_PRINT_INTEGER_ENABLE_64BIT}>
  PUBLIC LIBXR_PRINT_FLOAT_ENABLE_FIXED=$<BOOL:${LIBXR_PRINT_FLOAT_ENABLE_FIXED}>
  PUBLIC LIBXR_PRINT_FLOAT_ENABLE_DOUBLE=$<BOOL:${LIBXR_PRINT_FLOAT_ENABLE_DOUBLE}>
  PUBLIC LIBXR_PRINT_FLOAT_ENABLE_SCIENTIFIC=$<BOOL:${LIBXR_PRINT_FLOAT_ENABLE_SCIENTIFIC}>
  PUBLIC LIBXR_PRINT_FLOAT_ENABLE_GENERAL=$<BOOL:${LIBXR_PRINT_FLOAT_ENABLE_GENERAL}>
  PUBLIC LIBXR_PRINT_FLOAT_ENABLE_LONG_DOUBLE=$<BOOL:${LIBXR_PRINT_FLOAT_ENABLE_LONG_DOUBLE}>
  PUBLIC LIBXR_PRINT_ENABLE_WIDTH=$<BOOL:${LIBXR_PRINT_ENABLE_WIDTH}>
  PUBLIC LIBXR_PRINT_ENABLE_PRECISION=$<BOOL:${LIBXR_PRINT_ENABLE_PRECISION}>
)
